
import React, { useState, useMemo } from 'react';
import { Ticket, TicketStatus } from '../types';
import { 
  Wrench, 
  Clock, 
  CheckCircle2, 
  AlertCircle, 
  ChevronRight, 
  User, 
  Truck, 
  Filter, 
  Search, 
  X, 
  FileTerminal, 
  Cpu, 
  Wifi, 
  Activity, 
  Zap, 
  Camera,
  History
} from 'lucide-react';

interface Props {
  tickets: Ticket[];
  onUpdateTicket: (id: string, status: TicketStatus) => void;
}

const TechnicianTicketing: React.FC<Props> = ({ tickets, onUpdateTicket }) => {
  const [filter, setFilter] = useState<TicketStatus | 'ALL'>('ALL');
  const [activeLogTicketId, setActiveLogTicketId] = useState<string | null>(null);

  const filteredTickets = tickets.filter(t => filter === 'ALL' || t.status === filter);

  const activeTicket = useMemo(() => {
    return tickets.find(t => t.id === activeLogTicketId) || null;
  }, [tickets, activeLogTicketId]);

  const getStatusStyle = (status: TicketStatus) => {
    switch (status) {
      case TicketStatus.OPEN: return 'bg-rose-50 text-rose-600 border-rose-100';
      case TicketStatus.IN_PROGRESS: return 'bg-blue-50 text-blue-600 border-blue-100';
      case TicketStatus.RESOLVED: return 'bg-emerald-50 text-emerald-600 border-emerald-100';
      default: return 'bg-gray-50 text-gray-600 border-gray-100';
    }
  };

  const mockDiagnosticLogs = [
    { time: '08:12:45', module: 'COMM', level: 'ERROR', msg: 'Handshake timeout on primary cellular link' },
    { time: '08:14:10', module: 'POWER', level: 'WARN', msg: 'Voltage fluctuation detected in cabin interface (+/- 1.2V)' },
    { time: '08:14:32', module: 'DMS', level: 'INFO', msg: 'Camera recalibration triggered by unexpected lens flare' },
    { time: '08:15:00', module: 'GPS', level: 'CRITICAL', msg: 'Satellite fix lost (L1 band interference)' },
    { time: '08:15:22', module: 'SYS', level: 'INFO', msg: 'Automatic incident report generated by local behavioral engine' },
    { time: '08:16:05', module: 'COMM', level: 'INFO', msg: 'Switching to backup low-latency audio stream (PCM Raw)' },
  ];

  return (
    <div className="max-w-7xl mx-auto space-y-8 pb-12 relative flex">
      <div className={`flex-1 space-y-8 transition-all duration-500 ${activeLogTicketId ? 'pr-8 xl:pr-12 border-r border-gray-100' : ''}`}>
        <div className="flex justify-between items-end">
          <div>
            <div className="flex items-center gap-3 mb-2">
              <div className="bg-black p-2 rounded-xl text-white">
                <Wrench size={24} />
              </div>
              <h2 className="text-3xl font-bold tracking-tight text-zinc-900">Technician Portal</h2>
            </div>
            <p className="text-gray-500 font-medium">Managing hardware & communication integrity tickets.</p>
          </div>
          <div className="flex gap-2 bg-white p-1 rounded-xl border border-gray-100 shadow-sm">
            {(['ALL', ...Object.values(TicketStatus)] as const).map(s => (
              <button
                key={s}
                onClick={() => setFilter(s)}
                className={`px-4 py-1.5 rounded-lg text-xs font-bold transition-all ${filter === s ? 'bg-black text-white' : 'text-gray-400 hover:text-black hover:bg-gray-50'}`}
              >
                {s.replace('_', ' ')}
              </button>
            ))}
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-4 gap-8">
          <div className="lg:col-span-3 space-y-4">
            {filteredTickets.length > 0 ? filteredTickets.map((ticket) => (
              <div key={ticket.id} className={`bg-white rounded-[32px] border p-6 shadow-sm hover:shadow-md transition-all group ${activeLogTicketId === ticket.id ? 'border-black ring-1 ring-black/5' : 'border-gray-100'}`}>
                <div className="flex items-start justify-between mb-6">
                  <div className="flex items-center gap-4">
                    <div className={`p-3 rounded-2xl border ${getStatusStyle(ticket.status)}`}>
                      {ticket.status === TicketStatus.RESOLVED ? <CheckCircle2 size={24} /> : <AlertCircle size={24} />}
                    </div>
                    <div>
                      <div className="flex items-center gap-2">
                        <span className="text-[10px] font-black text-gray-300 uppercase tracking-widest">{ticket.id}</span>
                        <span className={`text-[10px] font-black px-2 py-0.5 rounded border uppercase ${getStatusStyle(ticket.status)}`}>
                          {ticket.status.replace('_', ' ')}
                        </span>
                      </div>
                      <h3 className="text-lg font-bold text-gray-900 mt-1">{ticket.issue}</h3>
                    </div>
                  </div>
                  <div className="text-right">
                    <p className="text-xs font-bold text-gray-400 uppercase tracking-widest flex items-center gap-1 justify-end">
                      <Clock size={12} /> {ticket.timestamp}
                    </p>
                  </div>
                </div>

                <div className="grid grid-cols-3 gap-6 py-6 border-y border-gray-50">
                  <div className="flex items-center gap-3">
                    <div className="w-10 h-10 bg-gray-50 rounded-full flex items-center justify-center text-gray-400 border border-gray-100">
                      <Truck size={20} />
                    </div>
                    <div>
                      <p className="text-[10px] font-bold text-gray-400 uppercase">Unit ID</p>
                      <p className="text-sm font-bold">{ticket.unitId}</p>
                    </div>
                  </div>
                  <div className="flex items-center gap-3">
                    <div className="w-10 h-10 bg-gray-50 rounded-full flex items-center justify-center text-gray-400 border border-gray-100">
                      <User size={20} />
                    </div>
                    <div>
                      <p className="text-[10px] font-bold text-gray-400 uppercase">Driver</p>
                      <p className="text-sm font-bold">{ticket.driverName}</p>
                    </div>
                  </div>
                  <div className="flex items-center gap-3">
                    <div className="w-10 h-10 bg-gray-50 rounded-full flex items-center justify-center text-gray-400 border border-gray-100">
                      <Wrench size={20} />
                    </div>
                    <div>
                      <p className="text-[10px] font-bold text-gray-400 uppercase">Assignee</p>
                      <p className="text-sm font-bold">{ticket.assignedTo}</p>
                    </div>
                  </div>
                </div>

                <div className="mt-6 flex justify-between items-center">
                  <div className="flex gap-2">
                    {ticket.status === TicketStatus.OPEN && (
                      <button 
                        onClick={() => onUpdateTicket(ticket.id, TicketStatus.IN_PROGRESS)}
                        className="px-4 py-2 bg-black text-white text-xs font-bold rounded-xl hover:bg-gray-800 transition-all shadow-md"
                      >
                        Start Repair
                      </button>
                    )}
                    {ticket.status === TicketStatus.IN_PROGRESS && (
                      <button 
                        onClick={() => onUpdateTicket(ticket.id, TicketStatus.RESOLVED)}
                        className="px-4 py-2 bg-emerald-600 text-white text-xs font-bold rounded-xl hover:bg-emerald-700 transition-all shadow-lg shadow-emerald-100"
                      >
                        Mark Resolved
                      </button>
                    )}
                  </div>
                  <button 
                    onClick={() => setActiveLogTicketId(activeLogTicketId === ticket.id ? null : ticket.id)}
                    className={`text-xs font-black uppercase tracking-widest transition-all flex items-center gap-2 px-4 py-2 rounded-xl border ${
                      activeLogTicketId === ticket.id ? 'bg-zinc-100 text-black border-zinc-200' : 'text-zinc-400 border-transparent hover:text-black hover:border-zinc-100'
                    }`}
                  >
                    <FileTerminal size={14} /> 
                    {activeLogTicketId === ticket.id ? 'Close Logs' : 'Full Diagnostic Log'} 
                    <ChevronRight size={14} className={`transition-transform ${activeLogTicketId === ticket.id ? 'rotate-90' : ''}`} />
                  </button>
                </div>
              </div>
            )) : (
              <div className="flex flex-col items-center justify-center py-40 bg-white rounded-[48px] border border-gray-100 text-gray-300">
                <Wrench size={48} strokeWidth={1} className="mb-4 opacity-20" />
                <p className="text-sm font-bold uppercase tracking-widest">No maintenance tickets found</p>
              </div>
            )}
          </div>

          <div className="space-y-6">
            <div className="bg-white p-6 rounded-[32px] border border-gray-100 shadow-sm">
              <h3 className="font-bold mb-4 flex items-center gap-2">
                <Filter size={18} className="text-gray-400" /> Maintenance Health
              </h3>
              <div className="space-y-4">
                <HealthStat label="Total Tickets" value={tickets.length} />
                <HealthStat label="Pending Repairs" value={tickets.filter(t => t.status !== TicketStatus.RESOLVED).length} color="text-rose-600" />
                <HealthStat label="Uptime Efficiency" value="98.2%" color="text-emerald-600" />
              </div>
            </div>

            <div className="bg-blue-600 p-8 rounded-[32px] shadow-2xl text-white relative overflow-hidden group">
              <div className="relative z-10">
                <h3 className="font-black text-xl mb-2">Hardware Integrity</h3>
                <p className="text-blue-100 text-xs leading-relaxed mb-6">
                  Automatic ticketing triggered by RTC feedback ensures communication failure downtime is minimized.
                </p>
                <button className="w-full py-3 bg-white text-blue-700 text-xs font-black rounded-2xl flex items-center justify-center gap-2 shadow-lg shadow-black/10 hover:bg-blue-50 transition-all">
                  Technician SOP-44
                </button>
              </div>
              <div className="absolute -bottom-10 -right-10 text-white/5 group-hover:scale-110 transition-transform duration-700">
                <Wrench size={200} />
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* RIGHT DRAWER: FULL DIAGNOSTIC LOG */}
      {activeTicket && (
        <div className="w-[480px] bg-zinc-950 text-white h-[calc(100vh-120px)] rounded-[40px] shadow-2xl flex flex-col border border-white/10 animate-in slide-in-from-right-8 duration-500 overflow-hidden sticky top-0">
           <div className="p-8 border-b border-white/5 bg-zinc-900/50">
              <div className="flex justify-between items-start mb-6">
                 <div>
                    <div className="flex items-center gap-2 mb-1">
                       <FileTerminal size={16} className="text-indigo-400" />
                       <span className="text-[10px] font-black uppercase tracking-[0.2em] text-zinc-500">System Telemetry Log</span>
                    </div>
                    <h3 className="text-xl font-black">{activeTicket.id} Diagnostic</h3>
                 </div>
                 <button 
                  onClick={() => setActiveLogTicketId(null)}
                  className="p-2 bg-white/5 hover:bg-white/10 rounded-xl text-zinc-400 transition-colors"
                 >
                    <X size={20} />
                 </button>
              </div>

              <div className="grid grid-cols-2 gap-4">
                 <div className="bg-white/5 p-4 rounded-2xl border border-white/5">
                    <p className="text-[9px] font-black uppercase tracking-widest text-zinc-500 mb-1">Hardware ID</p>
                    <p className="text-xs font-mono font-bold">NODE-TX-2241</p>
                 </div>
                 <div className="bg-white/5 p-4 rounded-2xl border border-white/5">
                    <p className="text-[9px] font-black uppercase tracking-widest text-zinc-500 mb-1">Firmware Rev.</p>
                    <p className="text-xs font-mono font-bold text-indigo-400">v4.2.0-PRO-BETA</p>
                 </div>
              </div>
           </div>

           <div className="flex-1 overflow-y-auto p-8 custom-scrollbar space-y-8">
              <section>
                 <h4 className="text-[10px] font-black uppercase tracking-[0.2em] text-zinc-500 mb-4 flex items-center gap-2">
                    <Zap size={12} className="text-amber-400" /> Critical Health Check
                 </h4>
                 <div className="grid grid-cols-2 gap-3">
                    <HealthCheckItem icon={Cpu} label="System Processor" status="NOMINAL" />
                    <HealthCheckItem icon={Wifi} label="LTE Connectivity" status="ERROR" isError />
                    <HealthCheckItem icon={Camera} label="DMS Sensor" status="WARN" isWarn />
                    <HealthCheckItem icon={Activity} label="Audio Feed" status="NOMINAL" />
                 </div>
              </section>

              <section>
                 <div className="flex items-center justify-between mb-4">
                    <h4 className="text-[10px] font-black uppercase tracking-[0.2em] text-zinc-500 flex items-center gap-2">
                       <History size={12} className="text-indigo-400" /> Raw Telemetry Events
                    </h4>
                    <span className="text-[9px] font-bold text-zinc-600 uppercase">Live Feed</span>
                 </div>
                 <div className="bg-black rounded-2xl border border-white/5 overflow-hidden">
                    <table className="w-full text-left text-[11px] font-mono">
                       <thead className="bg-white/5">
                          <tr className="text-zinc-500 border-b border-white/5">
                             <th className="px-4 py-2 font-black uppercase tracking-widest">TS</th>
                             <th className="px-4 py-2 font-black uppercase tracking-widest">MOD</th>
                             <th className="px-4 py-2 font-black uppercase tracking-widest">LOG</th>
                          </tr>
                       </thead>
                       <tbody className="divide-y divide-white/5">
                          {mockDiagnosticLogs.map((log, i) => (
                             <tr key={i} className="hover:bg-white/5 transition-colors">
                                <td className="px-4 py-3 text-zinc-500">{log.time}</td>
                                <td className="px-4 py-3">
                                   <span className={`font-black ${
                                      log.level === 'ERROR' ? 'text-rose-500' :
                                      log.level === 'CRITICAL' ? 'text-rose-500' :
                                      log.level === 'WARN' ? 'text-amber-500' : 'text-emerald-500'
                                   }`}>{log.module}</span>
                                </td>
                                <td className="px-4 py-3 text-zinc-300 leading-relaxed">{log.msg}</td>
                             </tr>
                          ))}
                       </tbody>
                    </table>
                 </div>
              </section>

              <div className="p-6 bg-indigo-600 rounded-3xl shadow-xl shadow-indigo-900/40">
                 <h5 className="text-sm font-black mb-2 flex items-center gap-2">
                    <Wrench size={14} /> Technician Protocol
                 </h5>
                 <p className="text-xs text-indigo-100 leading-relaxed mb-4">
                    Unit {activeTicket.unitId} is reporting severe GPS/LTE desynchronization. Field replacement of 5G antenna module is recommended.
                 </p>
                 <button className="w-full py-2 bg-white text-indigo-600 rounded-xl text-[10px] font-black uppercase tracking-widest hover:bg-indigo-50 transition-all">
                    Generate Repair Order
                 </button>
              </div>
           </div>
        </div>
      )}
    </div>
  );
};

const HealthCheckItem = ({ icon: Icon, label, status, isError, isWarn }: any) => (
  <div className="p-4 rounded-2xl bg-white/5 border border-white/5 flex flex-col justify-between h-24">
     <div className="flex justify-between items-start">
        <Icon size={16} className={isError ? 'text-rose-500' : isWarn ? 'text-amber-500' : 'text-emerald-500'} />
        <span className={`text-[8px] font-black px-1.5 py-0.5 rounded uppercase border ${
           isError ? 'bg-rose-500/10 border-rose-500/20 text-rose-500' :
           isWarn ? 'bg-amber-500/10 border-amber-500/20 text-amber-500' :
           'bg-emerald-500/10 border-emerald-500/20 text-emerald-500'
        }`}>
           {status}
        </span>
     </div>
     <p className="text-[10px] font-bold text-zinc-400 mt-2">{label}</p>
  </div>
);

const HealthStat = ({ label, value, color = "text-gray-900" }: any) => (
  <div className="p-4 bg-gray-50 rounded-2xl border border-gray-100">
    <p className="text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-1">{label}</p>
    <p className={`text-xl font-black ${color}`}>{value}</p>
  </div>
);

export default TechnicianTicketing;
